### ISSUE TITLE
OG Trust Ranks shouldn't appear if the rank changing feature thing is used...

### ISSUE THREAD

**Issue by Erimelowo** [RequiDev/OGTrustRanks#1]
Trusted and Known users can hide their ranks and appear as a user. However, with this mod, that doesn't work...
Tested with my friend on a Veteran User world creator "Mississauga"... He sees them as a regular User without the mod and I see them as a Veteran User thanks to the mod. I should see them as a User since they're hiding their rank tho...

**Comment by RequiDev** [comment]
Were you in an instance with them? If you're not in an instance with them, unfortunately, there is no way to hide it.

**Comment by Erimelowo** [comment]
Oh I see. Indeed, we weren’t in an instance with them.
