### ISSUE TITLE
Only trust rank recoloring is working

### ISSUE THREAD

**Issue by forever-and-a-day** [RequiDev/OGTrustRanks#3]
While nameplate/menu colors are changed to match the user's hidden trust rank, the text on both Veteran and Legendary users is still "Trusted User". 
![17d6deb9934b](https://user-images.githubusercontent.com/10383240/141732571-c2c7c070-1c12-473f-8f2d-d7ea589a8e36.jpg)

**Comment by RequiDev** [comment]
Should be fixed in the lastest release: https://github.com/RequiDev/OGTrustRanks/releases/tag/v1.1.5
